apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: '>=0.0.0'
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: backstage
              password: backstage123
              database: backstage
        primary:
          persistence:
            enabled: true
            size: 8Gi
          service:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
