apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-service.fullname" . }}
  labels: {{- include "sample-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector: {{- include "sample-service.selectorLabels" . | nindent 4 }}
